In [24]:
import numpy as np
import pandas as pd
from math import sqrt
from itertools import combinations

df= pd.read_csv("C:/Users/DOTSC75/Desktop/winequality-white.csv",sep=';')
Omega= pd.read_csv("C:/Users/DOTSC75/Desktop/winequality-white.csv",sep=';')
d=3
w_mean=dict()

for i in df.columns:
    m=np.mean(df[i])
    w_mean[i]=m 

for k, v in w_mean.items():
    df[k] = df[k].apply(lambda x: x - v)

df.head()
w_std=dict()
for i in df.columns:
    v=np.std(df[i])
    w_std[i]=v
    
for k, v in w_std.items():

    df[k] = df[k].apply(lambda x: x*(1/v))   



df= df.cov()
eigenValues, eigenVectors = np.linalg.eig(df)
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

pca=[]
for i in range(d):
    pca.append(eigenVectors[i])
pca=np.array(pca).reshape(len(eigenValues),d)
print('PCA Component:')
print(pca)

O=Omega.values
final=np.matmul(O, pca)
print('Original Dataset Dimension:',Omega.shape)
print('After PCA dataset Dimension:',final.shape)
print('After PCA datase sample:')
print(final)



PCA Component:
[[-0.15690447  0.56066866  0.20738436]
 [-0.03373494 -0.24413933 -0.10585624]
 [ 0.22355921  0.13041311 -0.63145048]
 [-0.20087123  0.10411772 -0.17079229]
 [-0.02428722  0.01606694 -0.52491466]
 [ 0.13119747 -0.70298193  0.12370469]
 [-0.22363601 -0.22960669 -0.03159628]
 [ 0.14175876  0.2700227  -0.01337672]
 [-0.1329443   0.28938115  0.44635554]
 [-0.32953335 -0.06510579  0.13195866]
 [-0.12037133 -0.69141866  0.24949503]
 [ 0.10632912  0.05395597 -0.0096488 ]]
Original Dataset Dimension: (4898, 12)
After PCA dataset Dimension: (4898, 3)
After PCA datase sample:
[[-38.12683723 -69.25726295   1.35483062]
 [-29.89321398 -41.53242663   2.15888644]
 [-21.35004798 -43.59302616   4.80105919]
 ...
 [-23.01711714 -47.91195974   4.84948639]
 [-24.22874503 -43.41319617   4.3733052 ]
 [-21.23572487 -41.16643567   4.83032025]]
