In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import math
import operator


df = pd.read_excel("D:/Dataset/Perceptron.xlsx",header=None)
df.head()

0   1  2
0  51  35 -1
1  24  81 -1
2  65  24 -1
3  27  32 -1
4  41  54 -1

In [43]:
w_0=0
w_1=0
w_2=0
l_r=.001
w_j=np.array((w_0,w_1,w_2))
# w_j=np.c_[w_j]
w_j=w_j.transpose()
cf_diag_sum=len(df)-1
epoch=0
while (cf_diag_sum!=len(df)):
    plus_one=0
    minus_one=0
    w_j=w_j
    print(w_j)
    for i in range(len(df)):
        x_j=np.array((i+1,df.at[i,0],df.at[i,1]))
       
        a= x_j.dot(w_j)
        if a>=0:
            y_h=1
        if a<0:
            y_h=-1

        y=df.at[i,2]
        if (y==1) and (y_h==1):
            plus_one=plus_one+1
        if (y==-1) and (y_h==-1):
            minus_one=minus_one+1
        d_w_j=(x_j.dot(l_r*(y-y_h)))
        w_j=w_j+d_w_j
        
    print(w_j)
    cf_diag_sum=plus_one+minus_one
    epoch=epoch+1
    print(cf_diag_sum, epoch)

[0 0 0]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[-0.002 -0.102 -0.07 ]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
[0.02  0.06  0.072]
18 1
[0.02  0.06  0.072]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[ 0.018 -0.042  0.002]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
[0.04  0.12  0.144]
18 2
[0.04  0.12  0.144]
[0.038 0.018 0.074]
[ 0.034 -0.03  -0.088]
[ 0.034 -0.03  -0.088]
[ 0.034 -0.03  -

[0.442 0.07  0.078]
[0.442 0.07  0.078]
[0.442 0.07  0.078]
17 33
[0.442 0.07  0.078]
[ 0.44  -0.032  0.008]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.436 -0.08  -0.154]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
[ 0.458  0.082 -0.012]
17 34
[ 0.458  0.082 -0.012]
[ 0.456 -0.02  -0.082]
[ 0.456 -0.02  -0.082]
[ 0.456 -0.02  -0.082]
[ 0.456 -0.02  -0.082]
[ 0.456 -0.02  -0.082]
[ 0.456 -0.02  -0.082]
[ 0.456 -0.02  -0.082]
[ 0.44  -0.06  -0.132]
[ 0.44  -0.06  -0.132]
[ 0.44  -0.06  -0.132]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.01 ]
[0.462 0.102 0.

[ 0.566 -0.116 -0.082]
[ 0.55  -0.156 -0.132]
[ 0.55  -0.156 -0.132]
[ 0.55  -0.156 -0.132]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
[0.572 0.006 0.01 ]
16 57
[0.572 0.006 0.01 ]
[ 0.57  -0.096 -0.06 ]
[ 0.57  -0.096 -0.06 ]
[ 0.57  -0.096 -0.06 ]
[ 0.57  -0.096 -0.06 ]
[ 0.57  -0.096 -0.06 ]
[ 0.57  -0.096 -0.06 ]
[ 0.57  -0.096 -0.06 ]
[ 0.554 -0.136 -0.11 ]
[ 0.554 -0.136 -0.11 ]
[ 0.554 -0.136 -0.11 ]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
[0.576 0.026 0.032]
17 58
[0.576 0.026 0.032]
[ 0.574 -0.076 -0.038]
[ 0.574 -0.076 -0.038]
[ 0.574 -0.076 -0.038]
[ 0.574 -0.076 -0.038]
[ 0.574 -0.076 -0.038]
[ 0.574 -0.076 -0.038]
[ 0.574 -0.076 -0.038]
[ 0.558 -0.116 -0.088]
[ 0.558 -0.116 -0.088]
[ 0.558 -0.116 -0.0

[ 0.662 -0.054 -0.074]
[ 0.662 -0.054 -0.074]
[ 0.662 -0.054 -0.074]
[ 0.662 -0.054 -0.074]
[ 0.662 -0.054 -0.074]
[ 0.662 -0.054 -0.074]
[ 0.662 -0.054 -0.074]
[ 0.646 -0.094 -0.124]
[ 0.646 -0.094 -0.124]
[ 0.646 -0.094 -0.124]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
[0.668 0.068 0.018]
17 85
[0.668 0.068 0.018]
[ 0.666 -0.034 -0.052]
[ 0.666 -0.034 -0.052]
[ 0.666 -0.034 -0.052]
[ 0.658 -0.088 -0.116]
[ 0.658 -0.088 -0.116]
[ 0.658 -0.088 -0.116]
[ 0.658 -0.088 -0.116]
[ 0.642 -0.128 -0.166]
[ 0.642 -0.128 -0.166]
[ 0.642 -0.128 -0.166]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
[ 0.664  0.034 -0.024]
16 86
[ 0.664  0.034 -0.024]
[ 0.662 -0.068 -0.094]
[ 0.662 -0.068 -0.094]
[ 0.662 -

17 108
[0.692 0.074 0.016]
[ 0.69  -0.028 -0.054]
[ 0.69  -0.028 -0.054]
[ 0.69  -0.028 -0.054]
[ 0.682 -0.082 -0.118]
[ 0.682 -0.082 -0.118]
[ 0.682 -0.082 -0.118]
[ 0.682 -0.082 -0.118]
[ 0.666 -0.122 -0.168]
[ 0.666 -0.122 -0.168]
[ 0.666 -0.122 -0.168]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
[ 0.688  0.04  -0.026]
16 109
[ 0.688  0.04  -0.026]
[ 0.686 -0.062 -0.096]
[ 0.686 -0.062 -0.096]
[ 0.686 -0.062 -0.096]
[ 0.686 -0.062 -0.096]
[ 0.686 -0.062 -0.096]
[ 0.686 -0.062 -0.096]
[ 0.686 -0.062 -0.096]
[ 0.67  -0.102 -0.146]
[ 0.67  -0.102 -0.146]
[ 0.67  -0.102 -0.146]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
[ 0.692  0.06  -0.004]
17 110
[ 0.692  0.06  -

[7.12000000e-01 6.00000000e-02 7.77156117e-16]
[ 0.71  -0.042 -0.07 ]
[ 0.71  -0.042 -0.07 ]
[ 0.71  -0.042 -0.07 ]
[ 0.71  -0.042 -0.07 ]
[ 0.71  -0.042 -0.07 ]
[ 0.71  -0.042 -0.07 ]
[ 0.696 -0.102 -0.17 ]
[ 0.696 -0.102 -0.17 ]
[ 0.696 -0.102 -0.17 ]
[ 0.696 -0.102 -0.17 ]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
[ 0.718  0.06  -0.028]
17 141
[ 0.718  0.06  -0.028]
[ 0.716 -0.042 -0.098]
[ 0.716 -0.042 -0.098]
[ 0.716 -0.042 -0.098]
[ 0.716 -0.042 -0.098]
[ 0.716 -0.042 -0.098]
[ 0.716 -0.042 -0.098]
[ 0.716 -0.042 -0.098]
[ 0.7   -0.082 -0.148]
[ 0.7   -0.082 -0.148]
[ 0.7   -0.082 -0.148]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
[ 0.722  0.08  -0.006]
17 

[ 0.756  0.076 -0.036]
17 162
[ 0.756  0.076 -0.036]
[ 0.754 -0.026 -0.106]
[ 0.754 -0.026 -0.106]
[ 0.754 -0.026 -0.106]
[ 0.754 -0.026 -0.106]
[ 0.754 -0.026 -0.106]
[ 0.754 -0.026 -0.106]
[ 0.754 -0.026 -0.106]
[ 0.738 -0.066 -0.156]
[ 0.738 -0.066 -0.156]
[ 0.718 -0.186 -0.196]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
16 163
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.74  -0.024 -0.054]
[ 0.732 -0.078 -0.118]
[ 0.732 -0.078 -0.118]
[ 0.732 -0.078 -0.118]
[ 0.732 -0.078 -0.118]
[ 0.716 -0.118 -0.168]
[ 0.716 -0.118 -0.168]
[ 0.716 -0.118 -0.168]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.026]
[ 0.738  0.044 -0.02

[ 0.766  0.066 -0.04 ]
[ 0.766  0.066 -0.04 ]
[ 0.766  0.066 -0.04 ]
[ 0.766  0.066 -0.04 ]
[ 0.766  0.066 -0.04 ]
17 189
[ 0.766  0.066 -0.04 ]
[ 0.764 -0.036 -0.11 ]
[ 0.764 -0.036 -0.11 ]
[ 0.764 -0.036 -0.11 ]
[ 0.764 -0.036 -0.11 ]
[ 0.764 -0.036 -0.11 ]
[ 0.764 -0.036 -0.11 ]
[ 0.764 -0.036 -0.11 ]
[ 0.748 -0.076 -0.16 ]
[ 0.748 -0.076 -0.16 ]
[ 0.748 -0.076 -0.16 ]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
[ 0.77   0.086 -0.018]
17 190
[ 0.77   0.086 -0.018]
[ 0.768 -0.016 -0.088]
[ 0.768 -0.016 -0.088]
[ 0.768 -0.016 -0.088]
[ 0.768 -0.016 -0.088]
[ 0.768 -0.016 -0.088]
[ 0.756 -0.094 -0.178]
[ 0.756 -0.094 -0.178]
[ 0.756 -0.094 -0.178]
[ 0.756 -0.094 -0.178]
[ 0.756 -0.094 -0.178]
[ 0.778  0.068 -0.036]
[ 0.778  0.068 -0.036]
[ 0.778  0.068 -0.036]
[ 0.778  0.068 -0.036]
[ 0.778  0.068 -0.036]
[ 0.778  0.068 -0.03

[ 0.78   0.02  -0.024]
[ 0.78   0.02  -0.024]
[ 0.78   0.02  -0.024]
16 216
[ 0.78   0.02  -0.024]
[ 0.778 -0.082 -0.094]
[ 0.778 -0.082 -0.094]
[ 0.778 -0.082 -0.094]
[ 0.778 -0.082 -0.094]
[ 0.778 -0.082 -0.094]
[ 0.778 -0.082 -0.094]
[ 0.778 -0.082 -0.094]
[ 0.762 -0.122 -0.144]
[ 0.762 -0.122 -0.144]
[ 0.762 -0.122 -0.144]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
[ 0.784  0.04  -0.002]
17 217
[ 0.784  0.04  -0.002]
[ 0.782 -0.062 -0.072]
[ 0.782 -0.062 -0.072]
[ 0.782 -0.062 -0.072]
[ 0.782 -0.062 -0.072]
[ 0.782 -0.062 -0.072]
[ 0.782 -0.062 -0.072]
[ 0.768 -0.122 -0.172]
[ 0.768 -0.122 -0.172]
[ 0.768 -0.122 -0.172]
[ 0.768 -0.122 -0.172]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[ 0.79  0.04 -0.03]
[

[ 0.778 -0.092 -0.132]
[ 0.778 -0.092 -0.132]
[ 0.778 -0.092 -0.132]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
[0.8  0.07 0.01]
17 237
[0.8  0.07 0.01]
[ 0.798 -0.032 -0.06 ]
[ 0.798 -0.032 -0.06 ]
[ 0.798 -0.032 -0.06 ]
[ 0.79  -0.086 -0.124]
[ 0.79  -0.086 -0.124]
[ 0.79  -0.086 -0.124]
[ 0.79  -0.086 -0.124]
[ 0.774 -0.126 -0.174]
[ 0.774 -0.126 -0.174]
[ 0.774 -0.126 -0.174]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
[ 0.796  0.036 -0.032]
16 238
[ 0.796  0.036 -0.032]
[ 0.794 -0.066 -0.102]
[ 0.794 -0.066 -0.102]
[ 0.794 -0.066 -0.102]
[ 0.794 -0.066 -0.102]
[ 0.794 -0.066 -0.102]
[ 0.794 -0.066 -0.102]
[ 0.794 -0.066 -0.102]
[ 0.778 -0.106 -0.152]
[ 0.778 -0.106 -0.152]
[ 0.778 -0.106 -0.152]
[ 0.8    0.056 -0

[ 0.794 -0.042 -0.08 ]
[ 0.794 -0.042 -0.08 ]
[ 0.78  -0.102 -0.18 ]
[ 0.78  -0.102 -0.18 ]
[ 0.78  -0.102 -0.18 ]
[ 0.78  -0.102 -0.18 ]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
[ 0.802  0.06  -0.038]
17 256
[ 0.802  0.06  -0.038]
[ 0.8   -0.042 -0.108]
[ 0.8   -0.042 -0.108]
[ 0.8   -0.042 -0.108]
[ 0.8   -0.042 -0.108]
[ 0.8   -0.042 -0.108]
[ 0.8   -0.042 -0.108]
[ 0.8   -0.042 -0.108]
[ 0.784 -0.082 -0.158]
[ 0.784 -0.082 -0.158]
[ 0.784 -0.082 -0.158]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
[ 0.806  0.08  -0.016]
17 257
[ 0.806  0.08  -0.016]
[ 0.804 -0.022 -0.086]
[ 0.804 -0.022 -0.086]
[ 0.804 -0.022 -0.086]
[ 0.804 -0.022 -0.086]
[ 0.804 -0.022 -0.08

[ 0.816 -0.092 -0.148]
[ 0.816 -0.092 -0.148]
[ 0.816 -0.092 -0.148]
[ 0.816 -0.092 -0.148]
[ 0.8   -0.132 -0.198]
[ 0.8   -0.132 -0.198]
[ 0.8   -0.132 -0.198]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
[ 0.822  0.03  -0.056]
17 281
[ 0.822  0.03  -0.056]
[ 0.82  -0.072 -0.126]
[ 0.82  -0.072 -0.126]
[ 0.82  -0.072 -0.126]
[ 0.82  -0.072 -0.126]
[ 0.82  -0.072 -0.126]
[ 0.82  -0.072 -0.126]
[ 0.82  -0.072 -0.126]
[ 0.804 -0.112 -0.176]
[ 0.804 -0.112 -0.176]
[ 0.804 -0.112 -0.176]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
[ 0.826  0.05  -0.034]
17 282
[ 0.826  0.05  -0.034]
[ 0.824 -0.052 -0.104]
[ 0.824 -0.052 -0.104]
[ 0.824 -0.052 -0.104]
[ 0.824 -0.052 -0.10

[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
[ 0.812  0.034 -0.01 ]
17 311
[ 0.812  0.034 -0.01 ]
[ 0.81  -0.068 -0.08 ]
[ 0.81  -0.068 -0.08 ]
[ 0.81  -0.068 -0.08 ]
[ 0.81  -0.068 -0.08 ]
[ 0.81  -0.068 -0.08 ]
[ 0.81  -0.068 -0.08 ]
[ 0.81  -0.068 -0.08 ]
[ 0.794 -0.108 -0.13 ]
[ 0.794 -0.108 -0.13 ]
[ 0.794 -0.108 -0.13 ]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
[0.816 0.054 0.012]
17 312
[0.816 0.054 0.012]
[ 0.814 -0.048 -0.058]
[ 0.814 -0.048 -0.058]
[ 0.814 -0.048 -0.058]
[ 0.806 -0.102 -0.122]
[ 0.806 -0.102 -0.122]
[ 0.806 -0.102 -0.122]
[ 0.806 -0.102 -0.122]
[ 0.79  -0.142 -0.172]
[ 0.79  -0.142 -0.172]
[ 0.79  -0.142 -0.172]
[ 0.812  0.02  -0.03 ]
[ 0.812  0.02  -0.03 ]
[ 0.812  0.02  -0.03 ]
[ 0.812  0.02  -0.03 ]
[ 0.812

[ 0.814 -0.036 -0.038]
[ 0.814 -0.036 -0.038]
[ 0.814 -0.036 -0.038]
[ 0.806 -0.09  -0.102]
[ 0.806 -0.09  -0.102]
[ 0.806 -0.09  -0.102]
[ 0.806 -0.09  -0.102]
[ 0.79  -0.13  -0.152]
[ 0.79  -0.13  -0.152]
[ 0.79  -0.13  -0.152]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
[ 0.812  0.032 -0.01 ]
17 329
[ 0.812  0.032 -0.01 ]
[ 0.81 -0.07 -0.08]
[ 0.81 -0.07 -0.08]
[ 0.81 -0.07 -0.08]
[ 0.81 -0.07 -0.08]
[ 0.81 -0.07 -0.08]
[ 0.81 -0.07 -0.08]
[ 0.81 -0.07 -0.08]
[ 0.794 -0.11  -0.13 ]
[ 0.794 -0.11  -0.13 ]
[ 0.794 -0.11  -0.13 ]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
[0.816 0.052 0.012]
17 330
[0.816 0.052 0.012]
[ 0.814 -0.05  -0.058]
[ 0.814 -0.05  -0.058]
[ 0.814 -0.05  -0.058]
[ 0.8

[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
17 361
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.818  0.006 -0.036]
[ 0.812 -0.124 -0.084]
[ 0.812 -0.124 -0.084]
[ 0.812 -0.124 -0.084]
[ 0.812 -0.124 -0.084]
[ 0.812 -0.124 -0.084]
[ 0.796 -0.164 -0.134]
[ 0.796 -0.164 -0.134]
[ 0.796 -0.164 -0.134]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
[ 0.818 -0.002  0.008]
17 362
[ 0.818 -0.002  0.008]
[ 0.816 -0.104 -0.062]
[ 0.816 -0.104 -0.062]
[ 0.816 -0.104 -0.062]
[ 0.816 -0.104 -0.062]
[ 0.816 -0.104 -0.062]
[ 0.816 -0.104 -0.062]
[ 0.816 -0.104 -0.062]
[ 0.8   -0.144 -0.112]
[ 0.8   -0.144 -0.112]
[ 0.8   -0.144 -0.112]
[0.822 0.018 0.03 ]


[ 0.832 -0.064 -0.112]
[ 0.832 -0.064 -0.112]
[ 0.816 -0.104 -0.162]
[ 0.816 -0.104 -0.162]
[ 0.816 -0.104 -0.162]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
[ 0.838  0.058 -0.02 ]
17 391
[ 0.838  0.058 -0.02 ]
[ 0.836 -0.044 -0.09 ]
[ 0.836 -0.044 -0.09 ]
[ 0.836 -0.044 -0.09 ]
[ 0.836 -0.044 -0.09 ]
[ 0.836 -0.044 -0.09 ]
[ 0.836 -0.044 -0.09 ]
[ 0.822 -0.104 -0.19 ]
[ 0.822 -0.104 -0.19 ]
[ 0.822 -0.104 -0.19 ]
[ 0.822 -0.104 -0.19 ]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
[ 0.844  0.058 -0.048]
17 392
[ 0.844  0.058 -0.048]
[ 0.842 -0.044 -0.118]
[ 0.842 -0.044 -0.118]
[ 0.842 -0.044 -0.118]
[ 0.842 -0.044 -0.118]
[ 0.842 -0.044 -0.118]
[ 0.842 -0.044 -0.11

[ 0.834 -0.006 -0.064]
[ 0.834 -0.006 -0.064]
[ 0.834 -0.006 -0.064]
[ 0.828 -0.136 -0.112]
[ 0.828 -0.136 -0.112]
[ 0.828 -0.136 -0.112]
[ 0.828 -0.136 -0.112]
[ 0.828 -0.136 -0.112]
[ 0.812 -0.176 -0.162]
[ 0.812 -0.176 -0.162]
[ 0.812 -0.176 -0.162]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
17 425
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.834 -0.014 -0.02 ]
[ 0.828 -0.144 -0.068]
[ 0.828 -0.144 -0.068]
[ 0.828 -0.144 -0.068]
[ 0.828 -0.144 -0.068]
[ 0.828 -0.144 -0.068]
[ 0.812 -0.184 -0.118]
[ 0.812 -0.184 -0.118]
[ 0.812 -0.184 -0.118]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
[ 0.834 -0.022  0.024]
17 426
[ 0.834 -0.022  0.02

[ 0.82  -0.158 -0.18 ]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
17 456
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.842  0.004 -0.038]
[ 0.836 -0.126 -0.086]
[ 0.836 -0.126 -0.086]
[ 0.836 -0.126 -0.086]
[ 0.836 -0.126 -0.086]
[ 0.836 -0.126 -0.086]
[ 0.82  -0.166 -0.136]
[ 0.82  -0.166 -0.136]
[ 0.82  -0.166 -0.136]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
[ 0.842 -0.004  0.006]
17 457
[ 0.842 -0.004  0.006]
[ 0.84  -0.106 -0.064]
[ 0.84  -0.106 -0.064]
[ 0.84  -0.106 -0.064]
[ 0.84  -0.106 -0.064]
[ 0.84  -0.106 -0.064]
[ 0.84  -0.106 -0.064]
[ 0.84  -0.106 -0.064]
[ 0.824 -0.146 -0.114]
[ 0.824 -0.146 -0.114]
[ 0.824 -0.146 -0.11

KeyboardInterrupt: 